opam-version: "2.0"
synopsis: "The Information-Theoretic Polyglot Language for Living Systems & Bio-P4"
maintainer: ["Erick Oduniyi <community@intelligent-interfaces.org>"]
authors: ["Erick Oduniyi"]
license: "MIT"
homepage: "https://github.com/Mathematical-Linguistics/neu"
bug-reports: "https://github.com/Mathematical-Linguistics/neu/issues"
depends: [
  "ocaml" {>= "5.0"}
  "dune" {>= "3.14"}
  "menhir" {>= "3.0"}
]
build: [
  ["dune" "subst"] {dev}
  [
    "dune"
    "build"
    "-p"
    name
    "-j"
    jobs
    "@install"
    "@runtest" {with-test}
  ]
]
